// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCud6aDxTZ4Ur2xQHV0CFr-tmdDmM_15o8',
    appId: '1:608265253829:web:939accdab2e0b049ef51ac',
    messagingSenderId: '608265253829',
    projectId: 'hiuproject-9609c',
    authDomain: 'hiuproject-9609c.firebaseapp.com',
    storageBucket: 'hiuproject-9609c.firebasestorage.app',
    measurementId: 'G-KKHY9LXJE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YLyqefhnQUmM5X9vJh7qgvMi8lq3Yhs',
    appId: '1:608265253829:android:14e96f44f4a855f8ef51ac',
    messagingSenderId: '608265253829',
    projectId: 'hiuproject-9609c',
    storageBucket: 'hiuproject-9609c.firebasestorage.app',
  );
}
